cache_created_successfully: "&2Keška byla úspěšně vytvořena."
cache_list: "&2Seznam kešek:"
cache_stats: "&2Statistiky kešky {}"
cache_stats_player: "&2Statistika hráče {}"
cache_removed_successfully: "&2Keška byla úspěšně smazána."
all_caches_removed_successfully: "&2Všechny kešky byly úspšně smazány."
config_reloaded: "&2Proběhl reload configu."
cache_playerdata_removed: "&2Data hráče {} byly úspešně smazány."
cache_data_and_stats_removed: "&2Data a statistiky kešek byly úspěšně smazány."
your_caches_found_count: "&2Počet tvých nalezených kešek: {}"
best_cache_searchers: "c2Nejlepší hledači kešek:"
help: "&2Nápověda."
cache_open_first: "&6Nalezl jsi kešku! Celkem máš {} / {}. Dostanes {} penazi."
cache_open_next: "&Tuto kešku už jsi nalezl."
cache_latest_open: "&6Hurá! Nalezl jsi poslední kešku!"
click_the_chest_block: "Klikni na block chest"
not_enough_permissions: "Not enough permissions"
edit_mode_on: "&2Editace kešek zapnuta"
edit_mode_off: "&2Editace kešek vypnuta"